version: 2

models:
  - name: dim_device
    columns:
      - name: device_key
        tests: [not_null, unique]
  - name: dim_metric
    columns:
      - name: metric_key
        tests: [not_null, unique]
  - name: dim_date
    columns:
      - name: date_key
        tests: [not_null, unique]
  - name: fct_readings
    tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 1
          max_value: 100000
    columns:
      - name: reading_id
        tests: [not_null, unique]
      - name: device_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_device')
              field: device_key
      - name: metric_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_metric')
              field: metric_key
      - name: value
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 500
          - dbt_utils.accepted_range:
              min_value: 0